### ISSUE TITLE
Khadas VIM3 Debian kernel 5.9 image misaligned at boot

### ISSUE THREAD

**Issue by anto** [khadas/fenix#103]
I posted the issue that I experienced on https://forum.khadas.com/t/devuan-on-khadas-vim3/9616.

As I mentioned on my last post, Fenix script offers 2 options to build the image:
1. U-Boot 2015 and kernel 4.9
2. U-Boot mainline and kernel mainline (5.9)

However, the result of compiling using those 2 options is that I always get the same U-Boot version. The serial console always shows “U-Boot 2015.01-g4752efb (Mar 19 2020 - 11:49:51)”. Is that perhaps the cause of the kernel image misaligned issue?

**Comment by hyphop** [comment]
clarify plz your booting !
a u using system from sd or write whole system to emmc ?
becouse if u start system from sd / uboot still start from emmc if it was presented on emmc
