### ISSUE TITLE
[Docker build] Script doesn't support host kernel which has binfmt_misc compiled in, instead of modularised

### ISSUE THREAD

**Issue by davorvr** [khadas/fenix#106]
I'm trying to run a Docker build. My host system that's running the container has `binfmt_misc` support, but not as a module - it's compiled into the kernel. Here's some output from my host system:
```
❯ uname -srvm  
Linux 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 14:19:36 UTC 2020 x86_64
❯ zcat /proc/config.gz | grep -i binfmt_misc
CONFIG_BINFMT_MISC=y
❯ cat /proc/sys/fs/binfmt_misc/status
enabled
```
And `update-binfmts` works in the Docker container, showing that it should be able to run any `binfmt_misc`-related stuff it needs:
```
khadas@62c1759fa107:~/fenix$ sudo update-binfmts -V
binfmt-support 2.2.0
```
And finally, here's the offending bit of code that should check that the host system has `binfmt_misc` loaded as a module OR compiled into the kernel, instead of just checking if `binfmt_misc` exists as a module. I would write a pull request instead of opening an issue, but I don't know how to test for this properly myself.
https://github.com/khadas/fenix/blob/ff19ccc5577d13054acfab41916526b34aa30021/config/functions/common-functions#L152-L170

**Comment by numbqq** [comment]
Hello @davorvr 

I have add a patch for this, can you help me to check on your side?

**Comment by davorvr** [comment]
Hello! Thank you, I have tried it out, but it still doesn't work - the problem seems to be with the fact that the `/proc/sys/fs/binfmt_misc` directory is empty in my docker container, but populated on my host system. While googling, I found [this GitHub issue concerning podman (some kind of docker alternative)](https://github.com/containers/podman/issues/4725), which contains some useful information. I am _not_ using podman, by the way, I just found the issue in a google search and it seemed relevant. Anyway, this got me to check the _binfmt_misc_ mountpoint on both my host system:
```shell
❯ mount | grep binfmt_misc
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13595)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
❯
```
And inside the container:
```shell
$ mount | grep binfmt_misc
$
```
And, finally, simply running `sudo mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc` inside the container fixes the problem, and rerunning `make` to start the build again works.

**Comment by davorvr** [comment]
I rewrote the check and submitted a pull request - please have a look at it here #108 
This works on my system with built-in binfmt_misc, but needs testing with modularised binfmt_misc to check that it doesn't break anything that used to work.

**Comment by davorvr** [comment]
@numbqq I see the PR is merged, thank you, the problem is solved!
