### ISSUE TITLE
Cannot flash newer VIM3 Ubuntu Server Legacy images with aml-burn-tool

### ISSUE THREAD

**Issue by davorvr** [khadas/fenix#109]
It works with `VIM3_Ubuntu-server-focal_Linux-4.9_arm64_EMMC_V0.9.5-200928.img` (Sep 28), but I've tested images from `VIM3_Ubuntu-server-focal_Linux-4.9_arm64_EMMC_V0.9.5-201013.img` (Oct 13) up until the latest image (Oct 17), and `aml-burn-tool` fails because `aml_image_v2_packer` has a CRC mismatch:
```
[Msg]Image package version 0x2
[ERR]f(AmlImagePack.cpp)L306:Image check error! CRC check failed!
[ERR]f(AmlImagePack.cpp)L1635:Image file check failed!
```
I've only tested these images so I'm not sure which is the last working image. Can you please verify?

EDIT: Images I build myself using Docker pass the CRC check! Here's the build config:
```shell
khadas@6c2045a33881:~/fenix$ make info

Version: 0.9.5
Current environment:
===========================================

#KHADAS_BOARD=VIM3
#VENDOR=Amlogic
#CHIP=A311D
#LINUX=4.9
#UBOOT=2015.01
#DISTRIBUTION=Ubuntu
#DISTRIB_RELEASE=focal
#DISTRIB_TYPE=server
#DISTRIB_ARCH=arm64
#INSTALL_TYPE=EMMC

===========================================
```

**Comment by numbqq** [comment]
Hello @davorvr 

> but I've tested images from VIM3_Ubuntu-server-focal_Linux-4.9_arm64_EMMC_V0.9.5-201013.img (Oct 13) up until the latest image (Oct 17), and aml-burn-tool fails because aml_image_v2_packer has a CRC mismatch:
[Msg]Image package version 0x2
[ERR]f(AmlImagePack.cpp)L306:Image check error! CRC check failed!
[ERR]f(AmlImagePack.cpp)L1635:Image file check failed!

The image you download from GitHub Action?

**Comment by davorvr** [comment]
Yes @numbqq

**Comment by numbqq** [comment]
OK. I checked and reprodued this. I will send a patch to fix this issue.

**Comment by numbqq** [comment]
I have send a patch to fix this. You can check the new firmware after GitHub Actions done.

**Comment by davorvr** [comment]
Yeah, that fixes it. Thank you!
