### ISSUE TITLE
make: build fails when building in setgid environments

### ISSUE THREAD

**Issue by ardnew** [khadas/fenix#126]
## Target environment

- VIM3
- u-boot mainline
- Linux mainline
- Ubuntu (Fossa) Server

## Description

When building on a file system that has setgid bit set (e.g., mode `2755`, `2775`, etc.), `make` will fail to build (`debs` make target, I think?) with the following error:

```
Info: Building debs...
Info: Building package: linux-u-boot-vim3-mainline
dpkg-deb: error: control directory has bad permissions 2775 (must be >=0755 and <=0775)
make: *** [Makefile:5: all] Error 2
```

My fenix source repository directory is `/usr/local/src/khadas/fenix`:

```
$ stat /usr/local/src/khadas/fenix
File: /usr/local/src/khadas/fenix
Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 10304h/66308d   Inode: 43122804    Links: 4
Access: (2775/drwxrwsr-x)  Uid: ( 1000/  andrew)   Gid: ( 1001/developer)    <--- HERE
Access: 2020-12-13 03:25:31.550678423 -0600
Modify: 2020-06-20 21:11:31.772355974 -0500
Change: 2020-12-13 03:25:08.914614106 -0600
Birth: -
```

I don't think there should be any problem with this file mode, as it does in fact have sufficient privileges, so this seems to be a spurious error.

## Fix

I worked around the issue by removing the setgid bit manually on the entire fenix source repository and then rebuilding:

```
$ pwd
/usr/local/src/khadas/fenix
$ chmod -R g-s .
$ make
```

I'm guessing it may be `dpkg-deb` that's actually raising this error (not one of the fenix scripts), but there may be a configuration setting that can be changed to account for this? Otherwise, the script _could_ remove the setgid bit itself before reaching this point. I'm not sure which file or directories need to have their mode changed.

**Comment by numbqq** [comment]
Thanks for your feedback. we will check this issue.
