### ISSUE TITLE
make: build fails to rsync /boot files in build chroot

### ISSUE THREAD

**Issue by ardnew** [khadas/fenix#127]
This issue took some digging to figure out, as the error message wasn't very clear. I'll explain as best as I understand it.

## Target environment

- VIM3
- u-boot mainline
- Linux mainline
- Ubuntu (Fossa) Server

## Steps

1. Ran `make` from my fenix source repository directory `/usr/local/src/khadas/fenix`
2. After building all the necessary packages, the script creates an SD/USB image file for rootfs, containing a DOS/VFAT boot partition (for `/boot`) and a Linux partition (for `/`)
3. Both partitions are mounted as loopback devices, with boot partition mounted on top of the root partition:
    ```
    $ mount
    ...
    /dev/loop15p2 on /usr/local/src/khadas/fenix/build/images/rootfs type ext4 (rw,relatime)
    /dev/loop15p1 on /usr/local/src/khadas/fenix/build/images/rootfs/boot type vfat (rw,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro)
    ```

4. The script attempts to `rsync` the files+attributes we just built to these mount points, **trying to preserve file permissions**
5. It first tries to copy the contents of `/` before copying the contents of `/boot`, so it must exclude `/boot` during this phase. The script uses (from `config/functions/build-rootfs:418`):
    ```
    rsync -aHWXh --exclude="/boot/*" --exclude="/dev/*" --exclude="/proc/*" --exclude="/run/*" --exclude="/tmp/*" \
                    --exclude="/sys/*" --info=progress2,stats1 $ROOTFS_TEMP/ $ROOTFS/
    ```
   - **Note, however, this only excludes the _contents_ of `/boot`, and not the directory itself.**
7. At this point, `make` fails with the following error:
    ```
    Info: Copying files to root directory...
    rsync: chown "/usr/local/src/khadas/fenix/build/images/rootfs/boot" failed: Operation not permitted (1)
              1.39G  71%  171.40MB/s    0:00:07 (xfr#60802, to-chk=0/82075)
    
    sent 1.40G bytes  received 1.24M bytes  164.64M bytes/sec
    total size is 1.95G  speedup is 1.40
    rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
    Cleanup...
    make: *** [Makefile:5: all] Error 23
    ```

## Workaround

For some reason, `rsync` refuses to change the file system attributes of the `/boot` directory itself (which is a separate device/mount point than the destination directory given to the `rsync` command). Maybe because of one of the following options:
 - `-X, --xattrs                preserve extended attributes`
 - `    --devices               preserve device files (super-user only)` (_**implied**_ with `-a`)
 - `    --specials              preserve special files` (_**implied**_ with `-a`)

Whatever the reason, a workaround is to tell `rsync` to exclude the `/boot` directory itself (in `config/functions/build-rootfs:418`): 

```
rsync -aHWXh --exclude="/boot" --exclude="/dev/*" --exclude="/proc/*" --exclude="/run/*" --exclude="/tmp/*" \
                --exclude="/sys/*" --info=progress2,stats1 $ROOTFS_TEMP/ $ROOTFS/
```

This is okay because the very next script command will `rsync` the `/boot` directory **and** its contents (from `config/functions/build-rootfs:421-429`:

```
# rsync /boot
info_msg "Copying files to /boot directory..."
if [[ $(findmnt --target $ROOTFS/boot -o FSTYPE -n) == vfat ]]; then
    # fat32
    rsync -rLtWh --info=progress2,stats1 $ROOTFS_TEMP/boot $ROOTFS
else
    # ext4
    rsync -aHWXh --info=progress2,stats1 $ROOTFS_TEMP/boot $ROOTFS
fi
```

## Patch

The following diff shows how to patch the issue with the suggested workaround (**1-line change!**):

```
$ pwd
/usr/local/src/khadas/fenix
$  git diff
diff --git a/config/functions/build-rootfs b/config/functions/build-rootfs
index 9e90c14..8b9fcb9 100644
--- a/config/functions/build-rootfs
+++ b/config/functions/build-rootfs
@@ -415,7 +415,7 @@ prepare_partitions()

info_msg "Copying files to root directory..."

-       rsync -aHWXh --exclude="/boot/*" --exclude="/dev/*" --exclude="/proc/*" --exclude="/run/*" --exclude="/tmp/*" \
+       rsync -aHWXh --exclude="/boot" --exclude="/dev/*" --exclude="/proc/*" --exclude="/run/*" --exclude="/tmp/*" \
                        --exclude="/sys/*" --info=progress2,stats1 $ROOTFS_TEMP/ $ROOTFS/

# rsync /boot
```

**Comment by numbqq** [comment]
Thanks for your feedback. we will check this issue.
