### ISSUE TITLE
edge no sound

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#128]
after apply all patches for 5.10, edge-v no sound.

after remove 2 patches sound back.

please refer to: https://github.com/zhangn1985/linux/commit/02667b05bab8490e52e02d1fc5b66ed38f3e0904

due to my build is too slow, thus I don't want to tell which one, but highly suspect `0066-WIP-ASoC-hdmi-codec-reorder-channel-allocation-list.patch`

**Comment by numbqq** [comment]
Thanks for your feedback! We will check.
