### ISSUE TITLE
debs released by numbqq only for xenial/arm64

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#13]
@numbqq  please release packages for other releases.

thank you.

**Comment by numbqq** [comment]
Hello zhangn1985,

Which package do you need?

**Comment by zhangn1985** [comment]
because only xenial/arm64 is buildable, please fix it.

or please comment and tell us the source code where they built from.

all of the packages release by you.

**Comment by numbqq** [comment]
Hi zhangn1985,

I will do this, but not now.

Thanks.

**Comment by zhangn1985** [comment]
thanks @numbqq
