### ISSUE TITLE
Build Ubuntu 16.04 firmware for Vim3

### ISSUE THREAD

**Issue by hai-h-nguyen** [khadas/fenix#131]
Hi, 

Is it possible to build Ubuntu 16.04 for Vim3? I need that specific version for my project because the higher versions do not work reliably with my camera sensor (a RealSense D435i camera).

**Comment by numbqq** [comment]
Hello @hai-h-nguyen 

We don't maintain Ubuntu 16.04 anymore. If you need that version, you can check the old version here: https://github.com/khadas/fenix/tree/v0.7

You can add the Ubuntu 16.04 packages yourself.

**Comment by hai-h-nguyen** [comment]
Hi, 

I tried but that v0.7 branch has the kernel v4.9 which is not supported by the camera SDK. It supports 4.8 and 4.10 unfortunately. Is there any way to overcome this?

**Comment by raffaellod** [comment]
@hai-h-nguyen unfortunately it looks like Amlogic only provides 4.9 patched kernels. Khadas provides more kernel patch sets, but those (currently at least) are all 5.x versions.
