### ISSUE TITLE
Fenix Build crash installing mesa - missing libllvm10

### ISSUE THREAD

**Issue by hwspeedy** [khadas/fenix#134]
Hi Khadas,

Below is the logfile from fenix build ubuntu 20.04 focal - mainline uboot+kernel for VIM3: 
1. Maybe it is a ubuntu repository bug/change? - libllvm10 being removed...
2. Maybe the downloaded mesa libs needs to be using llvm-10 instead of llvm-9

PS: Why is there still so many kernel patches for VIM3 - are they sent upstream for integration into the kernel? - would advancing to released kernel 5.10-7 remove alot of them?

Is it the same for u-boot-mainline?

Thanx for a great product and a lot of fun using the fenix scripts to create images and see the continued improvements.

BUILD-LOG:
Unpacking python3-wiringpi (3.11-1) ...
Setting up python3-wiringpi (3.11-1) ...
Info: Installing mesa...
Info: Installing libd3dadapter9-mesa_21.10.100-devel-0ubuntu1-20.04.1_arm64.deb in chroot...
Selecting previously unselected package libd3dadapter9-mesa:arm64.
(Reading database ... 128578 files and directories currently installed.)
Preparing to unpack .../libd3dadapter9-mesa_21.10.100-devel-0ubuntu1-20.04.1_arm64.deb ...
Unpacking libd3dadapter9-mesa:arm64 (21.10.100-devel-0ubuntu1-20.04.1) ...
dpkg: dependency problems prevent configuration of libd3dadapter9-mesa:arm64:
 libd3dadapter9-mesa:arm64 depends on libllvm10 (>= 1:9~svn298832-1-); however:
  **Package libllvm10 is not installed.**

dpkg: error processing package libd3dadapter9-mesa:arm64 (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Errors were encountered while processing:
 libd3dadapter9-mesa:arm64
Cleanup...
make: *** [Makefile:5: all] Error 1

**Comment by hwspeedy** [comment]
Adding libllvm10 to line 226 in the /fenix/config/config makes the scripts work again.
PACKAGE_LIST_MESA="libclang-cpp9 libclc-r600 libclc-amdgcn **libllvm10**"

I also noted that the build took longer time after changes to config - so maybe missing dependency for debootstrap - when there are changes to ubuntu repository? - make clean was used before make without success to rebuild debootstrap.

**Comment by numbqq** [comment]
Thanks for your feedback. You are right the package is missing.
