### ISSUE TITLE
linux/ doesn't exist if not pulled first

### ISSUE THREAD

**Issue by bpasu** [khadas/fenix#136]
in config_linux()

Need to check if linux kernel exist else it should pull.

https://github.com/khadas/fenix/blob/ec03d22af69753214c707ca2269bb0894d52ad12/config/functions/build#L339

**Comment by numbqq** [comment]
Thanks for your feedback. I will check.

**Comment by numbqq** [comment]
And you can `make kernel` first, and then `make kernel-config`
