### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dreamflyforever** [khadas/fenix#139]
build command：
`source env/setenv.sh config config-template.conf
DOWNLOAD_MIRROR=china make`

error message：

`Err:7 http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu focal Release                
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu focal Release' does not have a Release file.
`

Thank you if any help.

**Comment by numbqq** [comment]
Hello,

I can build on my side without problems. Have you changed the source code ?

> Err:7 http://ppa.launchpad.net/terry.guo/gcc-arm-embedded/ubuntu focal Release

What's this source ? We don't use it on Fenix. It's your local host source?

**Comment by numbqq** [comment]
Close due to no response.
