### ISSUE TITLE
some questions:

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#14]
1, for uboot code:
```
        "storeboot="\
            "cfgload;"\
            "ext4load mmc 1:5 1080000 zImage;ext4load mmc 1:5 10000000 uInitrd;ext4load mmc 1:5 20000000 dtb.img;booti 1080000 10000000 20000000;"\
            "run update;"\
            "\0"\
```
I guess this is for normal Android boot, but mmc 1:5 looks like sdcard partition 5? if it right, cfgload will load valid boot command for Android.
so this code means this logic.
if NOT Andoid boot; then try boot OS in sdcard, otherwise try update.
how does boot.ini look like?

2: uboot code:
```
        "recovery_from_sdcard="\
            "setenv bootargs ${bootargs} aml_dt=${aml_dt} recovery_part={recovery_part} recovery_offset={recovery_offset};"\
            "if fatload mmc 0 ${loadaddr} aml_autoscript; then autoscr ${loadaddr}; fi;"\
            "if fatload mmc 0 ${loadaddr} recovery.img; then "\
                    "if fatload mmc 0 ${dtb_mem_addr} dtb.img; then echo sd dtb.img loaded; fi;"\
                    "wipeisb; "\
                    "bootm ${loadaddr};fi;"\
            "\0"\
```
when reboot to update mode, aml_autocsript will be put into internal emmc fat partition, u-boot will run this script. if this script contain boot command for OS in sdcard, it will boot to it. right?
is ther any example for aml_autocsript?

**Comment by zhangn1985** [comment]
I  got 2nd answer from:
https://github.com/150balbes/Amlogic_s905/blob/master/README.md

**Comment by numbqq** [comment]
Hi zhangn1985,

> I guess this is for normal Android boot, but mmc 1:5 looks like sdcard partition 5

It's eMMC partition. You can check in u-boot.

OK....

Glad to see that.

I'm just replying...

**Comment by zhangn1985** [comment]
@numbqq thanks for you reply

so mmc 0 is sdcard?

https://github.com/khadas/linux/blob/khadas-vim-3.14.y/arch/arm64/boot/dts/partitions-multios.dtsi
https://github.com/khadas/linux/blob/khadas-vim-3.14.y/arch/arm64/boot/dts/partitions-linux.dtsi
https://github.com/khadas/linux/blob/khadas-vim-3.14.y/arch/arm64/boot/dts/partitions-android.dtsi

eMMC partition 5, I don't see any partition is boot in these dtsi.

is partition--.dtsi important?

**Comment by numbqq** [comment]
> eMMC partition 5, I don't see any partition 5(4?)is boot in these dtsi.

Partition 0,1,2 are defined in u-boot

https://github.com/khadas/u-boot/blob/khadas-vim-v2015.01/drivers/mmc/aml_emmc_partition.c#L107

> is partition--.dtsi important?

Yes, it is.

**Comment by zhangn1985** [comment]
understand right now. thank you very much. @numbqq mmc1:5 is boot partition in partition-android.dtsi.

this uboot code is for android boot.

but mismatches with partition-linux.dtsi... this is not important to me....

I will use multiboot aml-autoscript to boot OS from sdcard...

**Comment by zhangn1985** [comment]
@numbqq  it looks, if I want to keep pre-installed Android, and use multi-Boot for Linux on SDCard, I have to use same partition-android.dtsi. right?

**Comment by numbqq** [comment]
> it looks, if I want to keep pre-installed Android, and use multi-Boot for Linux on SDCard, I have to use same partition-android.dtsi. right?

No, for linux you shuold use `partition-linux.dtsi`

> when use fenix to build SD Boot image, dtb file is arch/arm64/boot/dts/kvim_linux.dtb

For linux the dtb is `kvim_linux.dtb`

**Comment by zhangn1985** [comment]
@numbqq 

When Android is installed on EMMC, so EMMC partitions follow partition-android.dtsi,
well I want to boot Linux from SDCard, dtb file is kvim_linux.dtb, partition dtsi is partition-linux.dtsi
Mismatches!!

**Comment by numbqq** [comment]
> well I want to boot Linux from SDCard, dtb file is kvim_linux.dtb, partition dtsi is partition-linux.dtsi

`kvim_linux.dtb` is only for eMMC installation, for SD/USB installation you don't need it.

Thanks.

**Comment by zhangn1985** [comment]
@numbqq if SD/USB installation Linux wants to read emmc, still need partition-android.dtsi, right?
after I carefully read the code, understand why partition-android.dtsi is important.

new question:
https://docs.khadas.com/vim1/BootFromExtMedia.html

```


    LibreELEC, Ubuntu with linux 3.14 you need Android M or latest Android N(V180207 or later) running on eMMC.
    Ubuntu with linux 4.9 need Android O running on eMMC.
```
why?
