### ISSUE TITLE
contribute an improvement, but not test on VIM.

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#15]
systemctl will read /run/systemd/reboot-param for reboot target, and will use syscall reboot send to kernel, finally to aml's reboot, 
https://github.com/systemd/systemd/blob/master/src/basic/reboot-util.c#L52-L65
https://github.com/khadas/linux/blob/Vim/drivers/amlogic/reset/gxbb_poweroff.c

so we can use systemd service to write some right value to reboot-param.

first: mkdir /etc/systemd/system/reboot.target.wants
2nd: create reboot-param.service to /etc/systemd/system/
```
[Unit]
Description=Reboot-Param
Requires=systemd-reboot.service
Before=systemd-reboot.service
#After=shutdown.target umount.target final.target
[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo update > /run/systemd/reboot-param" 
```
3rd: create soft link to  /etc/systemd/system/reboot.target.wants

you know I don't have my VIM-Linux worked, if that not work, that's because /run is unmounted  before systemctl read the file. maybe uncomment After line could work.

**Comment by numbqq** [comment]
Hi zhangn1985,

Why do you want to add `reboot-param.service` service? You want to pass parameters from kernel to u-boot?

Thanks.

**Comment by zhangn1985** [comment]
yes. usually we can use `reboot update` from command line. but if use UI to reboot, this service maybe better.

**Comment by zhangn1985** [comment]
I guess you need new app.
```
gdbus call --system --dest org.freedesktop.login1 --object-path /org/freedesktop/login1 --method org.freedesktop.login1.Manager.Reboot true/false
```
this command can execute without root

**Comment by zhangn1985** [comment]
如果要嵌入系统重启对话框，挺麻烦的。
https://github.com/mate-desktop/mate-session-manager/blob/master/mate-session/gsm-logout-dialog.c
而且还估计和lightdm有关，如果用户换一个dm，就全不一样了。
因为看code 最后是发给 mdm unix socket,但是服务端没找到。

**Comment by numbqq** [comment]
是的，不同的桌面环境也不一样，对这个不是太了解，还得再看看。
