### ISSUE TITLE
Moving to more recent LTS kernel ?

### ISSUE THREAD

**Issue by Pea13** [khadas/fenix#153]
Hello,

I would like to know why the VIM3 is 'locked' to kernel 4.9 instead of moving for example to a more LTS kernel ? (5.10)
What are the issues that block this move ? Is something planned to change this ?
Regards,

**Comment by raffaellod** [comment]
The vendor kernel is 4.9 probably because that’s what Amlogic provides. If you don’t like that old version, you can switch to mainline kernels, which Khadas provides patches for (here in Fenix). For example, I’m running 5.14.21 right now on my VIM3.
