### ISSUE TITLE
Where do you have the artifacts? (images)

### ISSUE THREAD

**Issue by rNoz** [khadas/fenix#156]
Hi,

I forked your repo and tried to build with actions, as you recommended in the forum. The problem is that the github staff has automatically disable such functionality for my fork.

Where can I find the built images? Eg. vim3 mainline kernel sd-usb, vim3 gnome emmc etc.

I think you should upload somewhere, so we avoid this mess to just update and use a recent version of the linux distribution for our vim3...

**Comment by numbqq** [comment]
For latest release, you can follow this docs to upgrade.

https://docs.khadas.com/vim3/HowToUpgradeTheSystem.html

For full release images, you can find here: https://dl.khadas.com/Firmware/VIM3/Ubuntu/
