### ISSUE TITLE
TS050 on bionic 5.12

### ISSUE THREAD

**Issue by frantic777** [khadas/fenix#157]
Hi,
I've bought Khadas VIM3 with TS050, and now trying to use it with bionic and mainline kernel. I've used fenix script to re-configure kernel and add TS050 module. But after I start VIM3 with this image after showing Khadas logo which fades away and no image being shown on the screen - only hdmi output works. I've tried to find any documentation with no success. What needs to be done to make VIM3 use TS050 in Ubuntu?
Thanks.

**Comment by numbqq** [comment]
Hello @frantic777 

The mainline kernel still does not support the TS050 screen. If you want to use it, you need to use the 4.9 kernel.

**Comment by frantic777** [comment]
Seriously? Then this is a rip-off and scam, very disappointing

**Comment by ZephyrLabs** [comment]
> Hello @frantic777
> 
> The mainline kernel still does not support the TS050 screen. If you want to use it, you need to use the 4.9 kernel.

it seems manjaro defconfig has already made some arragements to run the TS050 touchscreen, presuming that only the device tree needs to be updated.. 

here is the file:
https://gitlab.manjaro.org/manjaro-arm/packages/core/linux/-/blob/master/config#L5802

please consider taking some cues from it, it would be really nice to have TS050 in mainline kernel, so many software possibilties..

**Comment by tarhan** [comment]
@numbqq I'm sorry for newbie question. But I think many people who do not develop drivers for MIPI devices have same thoughts.
Support for TS050 panel added to mainline kernel over almost two years ago. Here: https://lwn.net/Articles/838981/  
I've heard that MIPI CSI/DSI API changed in kernels 5.x but I could not find detailed information about that. So I've thought that it is reason why Khadas or community could not port TS050 panel and OS08A10 easily to kernels 5.x
Question. **Are there any other reasons besides creating correct DTS entries to port driver?**

From general understanding ARM camera stack maybe GPU proprietary ISP need to be ported as part of pipeline for TS050 panel?
