### ISSUE TITLE
wrong patch name?

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#159]
https://github.com/khadas/fenix/blob/4f2ddd943c331acd411b3aa5579cb75cf3d4ce0e/packages/linux-mainline/patches/5.12/0054-Add-test_offset.patch#L4

感觉这个patch的名字错了，应该是 text_offset。

这个patch是为了配合厂商uboot使用的吗？

**Comment by yan-wyb** [comment]
名字是笔误，我们会修正它。这个补丁主要是为了我们emmc上4.9内核的uboot可以启动SD中主线的内核。具体可以参考fenix里面的启动脚本。

**Comment by zhangn1985** [comment]
谢谢解释。
