### ISSUE TITLE
discuss on gpu package build

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#17]
https://github.com/khadas/fenix/blob/34275e59e2fcf4c0b6c1a33ce17a215e3e259966/config/functions/build-gpu-deb#L29

1, for Debian no package libegl1
2, for Debian libgles2 is virtual package
3, suggest to use Conflicts, Provides with Replaces

```
		Replaces: libegl1-mesa, libgles2, aml-mali-905
		Provides: libegl1-mesa, libgles2, aml-mali-905
                Conflicts: libegl1-mesa, libgles2, aml-mali-905
```

**Comment by zhangn1985** [comment]
when install desktop, libgles2-mesa will replace this package.

**Comment by numbqq** [comment]
Hello zhangn1985,

> 1, for Debian no package libegl1

`libegl1` is in `Debian stretch`
```
stretch-backports (libs): Vendor neutral GL dispatch library -- EGL support 
1.0.0+git20180308-2~bpo9+1: arm64
```

> 3, suggest to use Conflicts, Provides with Replaces
		Replaces: libegl1-mesa, libgles2, aml-mali-905
		Provides: libegl1-mesa, libgles2, aml-mali-905
                Conflicts: libegl1-mesa, libgles2, aml-mali-905

I will try this, thank you~

**Comment by numbqq** [comment]
OK. When I update the `Conflicts, Provides and Replaces` GPU package failed to install.
```
dpkg: regarding .../linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-fbdev_0.3_arm64.deb containing linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-fbdev:
 libgles2-mesa:arm64 conflicts with libgles2
  linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-fbdev provides libgles2 and is to be installed.

dpkg: error processing archive /root/linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-fbdev_0.3_arm64.deb (--install):
 conflicting packages - not installing linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-fbdev

```

**Comment by zhangn1985** [comment]
I guess you already have libgles2-mesa installed, so can't install.

**Comment by zhangn1985** [comment]
libegl1 is real package, and libegl1-mesa is dummy.

questions:
linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-fbdev_0.3_arm64.deb  this package provides EGL, GLES2

when I check package: libgles2:arm64, I find it 
```
Conflicts: libgles2
Replaces: libgles2
Provides: libgles2
```
so if linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-fbdev_0.3_arm64.deb provides egl and gles, I guess, you can follow this way.

**Comment by zhangn1985** [comment]
this is my misunderstanding,close
