### ISSUE TITLE
Missing CONFIG_TASK_IO_ACCOUNTING

### ISSUE THREAD

**Issue by Pea13** [khadas/fenix#171]
Hello,

In order to user iotop (to do some measurements for etcd performances), i need the parameter CONFIG_TASK_IO_ACCOUNTING to be set in the config file of the kernel.
```
Could not run iotop as some of the requirements are not met:
- Linux >= 2.6.20 with
  - I/O accounting support (CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING)

```
Is it possible to add it in the config file for VIMx boards ? (CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT are already ok)
Regards,

**Comment by numbqq** [comment]
@Pea13 Thanks for your feedback, we will add it.
