### ISSUE TITLE
missing fbset in initramfs

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#18]
local-top script: khadas_init.sh requires fbset, but it not copied to initramfs

create file /etc/initramfs-tools/hook/fbset, and chmod +x
with below content:
```
#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

if [ -x /bin/fbset ]
then
	copy_exec /bin/fbset /bin

	LIBC_DIR=$(ldd /bin/fbset | sed -nr 's#.* => (/lib.*)/libc\.so\.[0-9.-]+ \(0x[[:xdigit:]]+\)$#\1#p')
	find -L "$LIBC_DIR" -maxdepth 1 -name 'libgcc_s.*' -type f | while read so; do
		copy_exec "$so"
	done
fi
```

**Comment by numbqq** [comment]
> local-top script: khadas_init.sh requires fbset, but it not copied to initramfs

`fbset` is in initramfs.

```
(initramfs) fbset -v
BusyBox v1.22.1 (Ubuntu 1:1.22.0-15ubuntu1) multi-call binary.

Usage: fbset [OPTIONS] [MODE]

Show and modify frame buffer settings
```

When VIMs bootup you will see the resolution set to `720p` first which is set in `khadas_init.sh`.

Thanks.

**Comment by zhangn1985** [comment]
OK, not in debian's initramfs....

**Comment by zhangn1985** [comment]
is  mali.ko required by initramfs?

**Comment by numbqq** [comment]
> not in debian's initramfs....

I will check this..

> is mali.ko required by initramfs?

Not required.

**Comment by zhangn1985** [comment]
@numbqq 我已经安装了debian+3/14到SD卡，已经能够启动到GUI，但是GUI似乎是放大了，MATE桌面的 panel 在屏幕外面，似乎是传给电视的画面稍微大了些。
我试过720P和1080P两种分辨率，都这样。

**Comment by zhangn1985** [comment]
我后来用1080p30hz，似乎好了，但不稳定，偶尔又会出问题。
可是我的电视的4K的，所以，能用4K是最好。是三星的UA50K.

但是我照着Android的设置抄到Linux这边还是不行。只显示右上角。缩放没有有作用。

```
fbset -fb /dev/fb0 -g 1920 1080 1920 3240 32
echo 2160p60hz420 > /sys/class/display/mode
echo 0x10001 > /sys/class/graphics/fb0/free_scale
echo 1 > /sys/class/graphics/fb0/freescale_mode
echo 0 0 1919 1079 > /sys/class/graphics/fb0/free_scale_axis
echo 0 0 3839 2159 > /sys/class/graphics/fb0/window_axis
echo 0 > /sys/class/graphics/fb1/free_scale
```

**Comment by numbqq** [comment]
4K显示效果很差的，图标文字都缩放的很小。我这边有的电视有问题就按上面缩放一下就可以了，你那个还不太确定什么原因。

**Comment by numbqq** [comment]
> not in debian's initramfs....

Debian确实有问题，使用你提供的那个脚本可以工作，谢谢～

**Comment by numbqq** [comment]
> 但是我照着Android的设置抄到Linux这边还是不行。只显示右上角。缩放没有有作用。

你是不是用的`4.9`的内核？ `4.9`内核不支持4K显示，设置为4K就只是在左上角显示1/4。
你可以试试`3.14`的内核，支持4K。

**Comment by zhangn1985** [comment]
我用的就是3.14， 不知怎么就是不行，我还是老老实实用1080p调整缩放吧。

**Comment by zhangn1985** [comment]
我感觉吧，我抄的那组Android 4K设置，framebuffer是1080p，是通过display缩放过去的。

但是缩放的`echo 0x10001 > /sys/class/graphics/fb0/free_scale` 不生效，具体填什么，试了很多，都不起作用，照着hdmi.sh做也不正确。

可以告诉我free_scale该怎么填吗？有文档么？

**Comment by zhangn1985** [comment]
@numbqq 搞清楚了，应该是驱动的bug
这些指令要按循序执行，下面是正确的4K指令循序
```
fbset -fb /dev/fb0 -g 1920 1080 1920 2160 32
echo 1 > /sys/class/graphics/fb0/freescale_mode
echo 0 0 1919 1079 > /sys/class/graphics/fb0/free_scale_axis
echo 0 0 3839 2159 > /sys/class/graphics/fb0/window_axis
echo 0x10001 > /sys/class/graphics/fb0/free_scale
echo 2160p60hz420 > /sys/class/display/mode
```

**Comment by zhangn1985** [comment]
@numbqq 还有个问题，我在debian stratch 3.14上安装了MATE桌面，但是背景全黑呀。。。

这个是为什么呢？

**Comment by zhangn1985** [comment]
@numbqq 还有个问题，我在debian stratch 3.14上安装了MATE桌面，但是背景全黑呀。。。

这个是为什么呢？
![img_20180714_225056](https://user-images.githubusercontent.com/832666/42725617-5b8da6a4-87b9-11e8-89d9-82e928dcce47.jpg)

**Comment by zhangn1985** [comment]
运行cube测试程序的时候，出现
`libEGL warning: DRI2 failed to authenticate`
这个问题怎么解决？

**Comment by zhangn1985** [comment]
`libEGL warning: DRI2 failed to authenticate`
这个问题的出现是因为对应的GL/EGL库不是libmali，修复链接即可，
但是还是报` eglGetError 0x3003 EGL_BAD_ALLOC`

**Comment by zhangn1985** [comment]
被这个黑屏还有硬件编解码搞到崩溃了，过一个礼拜再来。

**Comment by zhangn1985** [comment]
|img/tv|Sangsum 1080p|sangsum 4k|
|--------|--------------------|----------------|
|内置Android M|  画面超出显示器 |正常|
|Khadas Ubuntu Mate|画面超出显示器，通过缩放调整，界面背景黑屏，kodi仍需调整|1080P：画面超出显示器，通过缩放调整，界面背景黑屏，4K：界面背景黑屏， Kodi两种分辨率都无法正常工作|
|自制Debian Mate| N/A |4K：界面背景黑屏|

Khadas Ubuntu Mate: [下载地址](http://dl.khadas.com/Firmware/VIM1/Ubuntu/SD_USB/VIMs_Ubuntu-xenial_Linux-3.14_mate_arm64_SD-USB_2018-05-31.7z)  重启或关机内核空指针，初步怀疑和pulseaudio有关。

**Comment by numbqq** [comment]
> 还有个问题，我在debian stratch 3.14上安装了MATE桌面，但是背景全黑呀。。。

还没有试过Debian Mate桌面。Debian LXDE或XFCE会这样吗？

**Comment by zhangn1985** [comment]
@numbqq 试过xfce4，现象一样。

**Comment by numbqq** [comment]
Hello zhangn1985，

我会编译验证一下这个问题～

**Comment by zhangn1985** [comment]
@numbqq 小声的问一下，我看到[Odroid-c2的kernel](https://github.com/hardkernel/linux/tree/odroidc2-3.14.y) 的mali驱动和这里的不一样，多了[UMP](https://github.com/hardkernel/linux/tree/odroidc2-3.14.y/drivers/gpu/arm)。

另外我看到[fbturbo驱动](https://github.com/ssvb/xf86-video-fbturbo)也是需要UMP的。

把UMP弄到kvim上是否可行？又没有性能提升？（估计？）

**Comment by numbqq** [comment]
> 小声的问一下，我看到Odroid-c2的kernel 的mali驱动和这里的不一样，多了UMP。
另外我看到fbturbo驱动也是需要UMP的。
把UMP弄到kvim上是否可行？又没有性能提升？（估计？）

驱动版本不同吧，我们这个驱动是直接从Amlogic Buildroot那边拿过来的，没有做什么修改，至于`UMP`不是太了解。

**Comment by zhangn1985** [comment]
Odroid-c2 用的是S905, Kvim用的是S905X，我猜可行，不过Odroid-c2的kernel已经升级到了3.14.79，不好比较。

**Comment by numbqq** [comment]
> 试过xfce4，现象一样。

```
```

**Comment by zhangn1985** [comment]
我仅用了fenix编译出来的deb包，fenix配置除了`#INSTALL_TYPE=SD-USB`之外，没改了。

我不认为是DE的问题，觉得还是 缩放(0x10001)+xorg造成的。

如果不启用缩放，应该所有的DE都不会有问题。

**Comment by numbqq** [comment]
> 我不认为是DE的问题，觉得还是 缩放(0x10001)+xorg造成的。

我这边一台测试的电视缩放是没有问题的。你那边不缩放显示正常？

**Comment by zhangn1985** [comment]
除了画面超出电视之外，都正常。

**Comment by numbqq** [comment]
这个不太清楚。这边一台老的飞利浦电视会出现画面超出电视的现象，但是缩放之后正常。其他小米还有乐视的4K电视显示正常，一台LG的4K显示器也正常。

**Comment by numbqq** [comment]
> Khadas Ubuntu Mate: 下载地址 重启或关机内核空指针，初步怀疑和pulseaudio有关。

这个问题和声卡驱动有关系，我更新了下驱动，现在reboot好像不会报错了。

**Comment by zhangn1985** [comment]
@numbqq 那奇怪了，难道是我的启动脚本有问题？

我是这么启动的，拿你们发布的ubunut mate 为例子。
1， dd 到USB
1.1， 把boot分区的dtb/kvm_android.dtb复制为dtb.img，这步是因为第五步无法启动（卡很久没反应）
2， 插入到VIM的USB口
3，使用串口进入u-boot
4，输入`usb start`
5， 输入启动命令：
https://github.com/khadas/fenix/blob/973c37b696236253b54564a3a16672c1e5dfa3fc/config/bootscripts/s905_autoscript.cmd#L1-L10

**Comment by zhangn1985** [comment]
看代码kvim_linux.dtb 和 kvim_android.dtb只有 partition的区别。。。我可以试一下。

**Comment by zhangn1985** [comment]
哎～～～

**Comment by zhangn1985** [comment]
尝试了debian 10 + Linux-5.2.5+mesa 19.1.2 + lima enabled。
Sumsang 1080p TV：1080p不正常，画面超出显示器，1680p正常
Sumsang 4K TV： 4K 显示器提示不支持的模式，1080p正常。

目前Lima还不能满足日常使用。

**Comment by numbqq** [comment]
> Sumsang 1080p TV：1080p不正常，画面超出显示器，1680p正常

有试过显示器吗？好像有的电视会出现超出边界的情况，我们这边的一台飞利浦的电视就是这样。

> Sumsang 4K TV： 4K 显示器提示不支持的模式，1080p正常。

现在主线好像支持4K分辨率了吧？ 提示不支持是lima的原因吗？

**Comment by zhangn1985** [comment]
@numbqq 电脑显示器正常。4K倒是不知道，目前没有4K的显示器用于测试。

**Comment by numbqq** [comment]
我很早之前测试过4K显示，是正常的。

lima现在在X11下可以工作了吗？之前测试X11有很多问题。

**Comment by zhangn1985** [comment]
不可以，lima-18.3.6 + desktop patch，勉强可以，但UI渲染很慢，
mesa-19.1.2 不需要patch，但是桌面只有背景，没有其他的东西。

如果你想试一下，我有编译好的debs.

https://github.com/zhangn1985/lima_gpu_drv

```
Section "ServerFlags"
        Option  "AutoAddGPU" "off"
        Option "Debug" "dmabuf_capable"
EndSection

Section "OutputClass"
        Identifier "Meson"
        MatchDriver "meson"
        Driver "modesetting"
        Option "PrimaryGPU" "true"
EndSection
```

https://gitlab.freedesktop.org/lima/mesa/issues/96
https://gitlab.freedesktop.org/lima/mesa/issues/82
https://gitlab.freedesktop.org/lima/mesa/issues/92

**Comment by zhangn1985** [comment]
我略微搜索了一下，lima的进展要比panfrost 快。

等这个https://gitlab.freedesktop.org/lima/mesa/issues/85 关闭了就差不多可用了吧。

**Comment by numbqq** [comment]
> 如果你想试一下，我有编译好的debs.

谢谢！

> 我略微搜索了一下，lima的进展要比panfrost 快。
> 等这个https://gitlab.freedesktop.org/lima/mesa/issues/85 关闭了就差不多可用了吧。
估计还得在等段时间

**Comment by numbqq** [comment]
Hello @zhangn1985 ,

能否方便提供一下你的邮箱？

**Comment by zhangn1985** [comment]
@outlook.com

**Comment by numbqq** [comment]
@zhangn1985 

确认下 是`zhangn1985@outlook.com`吗？ 好像邮件发不出去？

**Comment by zhangn1985** [comment]
我给你邮件了。

**Comment by zhangn1985** [comment]
https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1699  WIP: lima: ppir: add control flow support
