### ISSUE TITLE
VIMs-add-gpiomem-support.patch broken for VIM3 since 5.16

### ISSUE THREAD

**Issue by mc-fu** [khadas/fenix#192]
Hi all,

the VIMs-add-gpiomem-support.patch is broken since version 5.16 for VIM3, as wrong registers are given in the dts file. For VIM3 this should be:

for gpiomem: reg = <0x0 0xff634000 0x0 0x1000>;
and for gpiomem_ao: reg = <0x0 0xff800000 0x0 0x1000>;

Since 5.16 wrong registers 0xda834000 (gpiomem) and 0xc8100000 (gpiomem_ao) are given in the patchfile for VIM3 which results in crashing gpio readall e.g.

Best regards
mc

**Comment by yan-wyb** [comment]
I have fix it . You can upgrade you code and build again.
