### ISSUE TITLE
Building Ubuntu 22.04 for Edge 2 cannot find mpp-rockchip / rga-rockchip

### ISSUE THREAD

**Issue by pitchaya** [khadas/fenix#209]
I'm building with the following parameters
***********************PARAMETERS************************
Fenix Version:         1.1.2
Khadas Board:          Edge2
Uboot Version:         2017.09
Uboot Configuration:   khadas-edge2-rk3588s_defconfig
Uboot Branch:          khadas-edges-v2017.09-release-v1.0.0
Linux Version:         5.10
Linux Configuration:   kedges_defconfig
Linux DTB:             arch/arm64/boot/dts/rockchip/rk3588s-khadas-edge2.dtb
Linux Branch:          khadas-edges-5.10.y-release-v1.0.0
Distribution:          Ubuntu
Distribution Release:  jammy
Distribution Type:     xfce
Distribution Arch:     arm64
Install Type:          EMMC
Final Image:           edge2-ubuntu-22.04-xfce-linux-5.10-fenix-1.1.2-221001-emmc-develop.img
*********************************************************

inside fenix Docker.

The script is trying to find mpp-rockchip, but failing

--2022-10-01 12:46:39--  https://github.com/yan-wyb//mpp-rockchip/archive/77565ada034de8babfac06677eb1dff0f1ff79e0.tar.gz
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-01 12:46:40 ERROR 404: Not Found.

It didn't get to rga-rockchip, but I suspect that it will has a problem as well.

Regards,

**Comment by numbqq** [comment]
Hello @pitchaya 

Already  fixed, please update your source code to check again.
