### ISSUE TITLE
another question about buildroot.

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#21]
Amlogic发布的buildroot编译出来的aml_upgrade_package.img，怎么烧入到eMMC？

比较了一下，编译出来的和 [image_upgrade ](https://github.com/khadas/images_upgrade) 类似，又有些许不同。

请问，有哪些注意事项呢？

**Comment by numbqq** [comment]
直接用windows下工具烧录就行

https://docs.khadas.com/zh-cn/vim1/UpgradeViaUSBCable.html#%E9%80%9A%E8%BF%87Windows%E5%8D%87%E7%BA%A7%E5%9B%BA%E4%BB%B6

**Comment by zhangn1985** [comment]
谢谢
