### ISSUE TITLE
VIM3 linux-mainline-6.0 build failure

### ISSUE THREAD

**Issue by algoideas** [khadas/fenix#214]
drivers/gpu/drm/meson/meson_viu.c:64:9: internal compiler error: Illegal instruction
   64 |         COEFF_NORM(0.181873),   COEFF_NORM(0.611831),   COEFF_NORM(0.061765),
      |         ^~~~~~~~~~
0x7f24e08a208f ???
        /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
make[5]: *** [scripts/Makefile.build:249: drivers/gpu/drm/meson/meson_viu.o] Error 1
make[5]: *** Waiting for unfinished jobs....

**Comment by yan-wyb** [comment]
Did you make any changes?

**Comment by algoideas** [comment]
Not any change

**Comment by algoideas** [comment]
env problem，it has been solved

**Comment by Airtau** [comment]
> env problem，it has been solved

I have the same problem. You can describe your solution. Thank`s.
