### ISSUE TITLE
fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory

### ISSUE THREAD

**Issue by kooksung930** [khadas/fenix#218]
Hello, I tried to generate image file. (ubuntu22.04-gnome for VIM4)

However, I got error like below from yesterday.

fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory

So, I failed to generate the file.

The similar errors are shown in generating ubuntu20.04.

-------------------------------------------------------------------------
The whole errors are like below:
In file included from drivers/gpu/arm/midgard/mali_kbase_cache_policy.h:29,
                 from drivers/gpu/arm/midgard/mali_kbase_cache_policy.c:26:
drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
  CC [M]  drivers/gpu/arm/midgard/mali_kbase_config.o
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_cache_policy.o] Error 1
make[5]: *** Waiting for unfinished jobs....
bcm SDIO driver configured
In file included from drivers/gpu/arm/midgard/mali_kbase_mem_pool_group.c:22:
./drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_mem_pool_group.o] Error 1
In file included from drivers/gpu/arm/midgard/mali_kbase_gpuprops.c:26:
./drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from drivers/gpu/arm/midgard/mali_kbase_native_mgm.c:26:
./drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_gpuprops.o] Error 1
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_native_mgm.o] Error 1
In file included from drivers/gpu/arm/midgard/mali_kbase_ctx_sched.c:22:
./drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_ctx_sched.o] Error 1
In file included from drivers/gpu/arm/midgard/mali_kbase_pm.c:26:
./drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_pm.o] Error 1
In file included from drivers/gpu/arm/midgard/mali_kbase_mem.c:36:
./drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_mem.o] Error 1
In file included from drivers/gpu/arm/midgard/mali_kbase_config.c:22:
./drivers/gpu/arm/midgard/mali_kbase.h:48:10: fatal error: uapi/gpu/arm/midgard/mali_base_kernel.h: No such file or directory
   48 | #include <uapi/gpu/arm/midgard/mali_base_kernel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
  AR      drivers/gpu/trace/built-in.a
make[5]: *** [scripts/Makefile.build:284: drivers/gpu/arm/midgard/mali_kbase_config.o] Error 1
make[4]: *** [scripts/Makefile.build:552: drivers/gpu/arm/midgard] Error 2
make[3]: *** [scripts/Makefile.build:552: drivers/gpu/arm] Error 2
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:552: drivers/gpu] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1857: drivers] Error 2
make[1]: Leaving directory '/home/kooksung/Downloads/install_ubuntu/fenix/build/linux'
make: *** [Makefile:2: all] Error 2

**Comment by numbqq** [comment]
Hello @kooksung930 

Please update the kernel and try again.
