### ISSUE TITLE
Mali errors

### ISSUE THREAD

**Issue by Tommy21st** [khadas/fenix#24]
I am having some errors with updated script, using ubuntu 18.04., didn't have any errors few weeks ago.

The script didn't create any image.

This is the output in terminal: Info: Installing linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb in chroot...
Selecting previously unselected package linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11.
(Reading database ... 102336 files and directories currently installed.)
Preparing to unpack .../linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb ...
Unpacking linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11 (0.5) ...
dpkg: error processing archive /root/linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb (--install):
 trying to overwrite '/usr/include/EGL/egl.h', which is also in package libegl1-mesa-dev:arm64 18.0.5-0ubuntu0~18.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /root/linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb
Cleanup...
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

This isn't closed issue, i did edit and now it says it's closed.

**Comment by Tommy21st** [comment]
I am having some errors with updated script, using ubuntu 18.04., didn't have any errors few weeks ago.

The script didn't create any image.

This is the output in terminal: Info: Installing linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb in chroot...
Selecting previously unselected package linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11.
(Reading database ... 102336 files and directories currently installed.)
Preparing to unpack .../linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb ...
Unpacking linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11 (0.5) ...
dpkg: error processing archive /root/linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb (--install):
trying to overwrite '/usr/include/EGL/egl.h', which is also in package libegl1-mesa-dev:arm64 18.0.5-0ubuntu0~18.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
/root/linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb
Cleanup...
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by Tommy21st** [comment]
I am having some errors with updated script, using ubuntu 18.04., didn't have any errors few weeks ago.

The script didn't create any image.

This is the output in terminal: Info: Installing linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb in chroot...
Selecting previously unselected package linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11.
(Reading database ... 102336 files and directories currently installed.)
Preparing to unpack .../linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb ...
Unpacking linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11 (0.5) ...
dpkg: error processing archive /root/linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb (--install):
trying to overwrite '/usr/include/EGL/egl.h', which is also in package libegl1-mesa-dev:arm64 18.0.5-0ubuntu0~18.04.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
/root/linux-gpu-amlogic-s905x-arm-mali-m450-r7p0-x11_0.5_arm64.deb
Cleanup...
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

This isn't closed issue, i did edit and now it says it's closed.

**Comment by numbqq** [comment]
Hello @Tommy21st,

This issue has been fixed, please update your repo and try again.

Thanks.
