### ISSUE TITLE
archives/hwpacks/video-firmware/Amlogic/meson': No such file or directory

### ISSUE THREAD

**Issue by andreyf2** [khadas/fenix#25]
Hello. When i was trying to build linux image with fenix, it stops with Error:
 cp: cannot stat 'archives/hwpacks/video-firmware/Amlogic/meson': No such file or directory

this is "log" 
  ........
  LD [M]  sound/usb/snd-usbmidi-lib.ko
  LD [M]  sound/xen/snd_xen_front.ko
make[1]: Leaving directory '/home/khadas/fenix/build/linux-mainline-4.20.3'
Info: Building debs...
Info: Build board deb...
Image Name:   S912 autoscript
Created:      Fri Jan 18 22:56:51 2019
Image Type:   AArch64 Linux Script (uncompressed)
Data Size:    5129 Bytes = 5.01 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 5121 Bytes = 5.00 kB = 0.00 MB
Image Name:   Amlogic autoscript
Created:      Fri Jan 18 22:56:51 2019
Image Type:   AArch64 Linux Script (uncompressed)
Data Size:    654 Bytes = 0.64 kB = 0.00 MB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 646 Bytes = 0.63 kB = 0.00 MB
  adding: aml_autoscript (deflated 65%)
  adding: aml_autoscript.txt (deflated 72%)
/home/khadas/fenix/build/linux-mainline-4.20.3
cp: cannot stat 'archives/hwpacks/video-firmware/Amlogic/meson': No such file or directory
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

this is my configuration 

Choose install type:
Force set to install-SD-USB
===========================================
#VERSION: 0.5

#KHADAS_BOARD=VIM2
#VENDOR=Amlogic
#CHIP=S912
#LINUX=mainline
#UBOOT=mainline
#DISTRIBUTION=Ubuntu
#DISTRIB_RELEASE=xenial
#DISTRIB_TYPE=mate
#DISTRIB_ARCH=arm64
#INSTALL_TYPE=SD-USB

===========================================

Environment setup done.
Type 'make' to build.

I`v tried to build it with Docker,  but Error is the same. Then i run under root: make image:
This script requires root privileges, trying to use sudo, please enter your passowrd!
sudo -E ./scripts/make_image.sh
Info: Build host: bionic
Info: Running in container: docker
Info: apt-cacher is disabled in containers, set NO_APT_CACHER=no to override
Info: Image install type: SD-USB
losetup: /home/khadas/fenix/build/images/VIM2_Ubuntu-mate-xenial_Linux-4.20.3_arm64_SD-USB_V20190118.img: failed to set up loop device: No such file or directory
Makefile:22: recipe for target 'image' failed
make: *** [image] Error 1

What it can be, and how can i solve this?

**Comment by numbqq** [comment]
Hello @andreyf2 ,

Thanks for your feedback.:)

This issue has been fixed. eda49b628c17942214494a47051a56f504e9e116

Please update your repo and try again.

**Comment by andreyf2** [comment]
Looks like it hasn`t. 

IMAGE: /home/khadas/fenix/build/images/VIM2_Ubuntu-mate-bionic_Linux-4.20.3_arm64_SD-USB_V20190120.img  is ready!
Cleanup...

Thank you.

**Comment by numbqq** [comment]
It's strange, when I updated, my build host don't have this issue anymore.

What's your build host?

**Comment by numbqq** [comment]
OK. The same build host to mine.

Can you help me to do one more test? Remove the following commits and try again.

```
$ git branch test-build
$ git checkout test-build
$ git revert a277199a69a738f4e7e3760ed093ecfe53f441b6
$ git revert 7ef78da026587e3aa49aabeed79b7243f365bc4a
$ make
```

**Comment by andreyf2** [comment]
It`s not the same as previous one..

Selecting previously unselected package linux-board-package-xenial-mainline-vim2-sd-usb.
(Reading database ... 120906 files and directories currently installed.)
Preparing to unpack .../linux-board-package-xenial-mainline-vim2-sd-usb_0.5_arm64.deb ...
Unpacking linux-board-package-xenial-mainline-vim2-sd-usb (0.5) ...
Replacing files in old package base-files (9.4ubuntu4.7) ...
Replacing files in old package watchdog (5.14-3ubuntu0.16.04.1) ...
Setting up linux-board-package-xenial-mainline-vim2-sd-usb (0.5) ...
Processing triggers for initramfs-tools (0.122ubuntu8.14) ...
update-initramfs: Generating /boot/initrd.img-4.20.3
Unsupported ioctl: cmd=0x5331
qemu: Unsupported syscall: 267
/bin/sync: error syncing '/boot/initrd.img-4.20.3': Function not implemented
dpkg: error processing package initramfs-tools (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (229-4ubuntu21.15) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 initramfs-tools
Cleanup...
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by numbqq** [comment]
Oops, I can't reproduce this issue since last patch...

**Comment by andreyf2** [comment]
Maybe i`m doing sth wrong... But actually i delete and then download fenix and packages again, so them must update. Sorry for my tenses..

**Comment by numbqq** [comment]
OK. I will look into this issue when I meet it again...
