### ISSUE TITLE
enable lima driver?

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#30]
I find lima driver patches, but they are not enabled, do you have plan to enable it?

**Comment by numbqq** [comment]
Hello @zhangn1985 ,

Lima still can't work well with X11, you can find some information here: https://gitlab.freedesktop.org/lima/linux/issues/19

**Comment by zhangn1985** [comment]
understand. How aboult mali driver? is it already enabled?

**Comment by numbqq** [comment]
For Ubuntu xenial mate it is enabled(long time ago, not test with latest mainline kernel), but for bionic is not due to issues with xf86-video-armsoc.
But the performance of mali X11 driver is not good.

**Comment by zhangn1985** [comment]
but I can't find any mali*.ko in build/ when build mainline kernel. why? it's builtin?

**Comment by numbqq** [comment]
Mainline mali driver is in package https://github.com/khadas/fenix/tree/master/packages/meson-gx-mali-450

After build, you can find mali.ko in `build/meson-gx-mali-450-b16af106e09f85705ca0519dee4b920d6216b663`

**Comment by zhangn1985** [comment]
```
ning@ning-debian:~/source/fenix/build$ ls -l
总用量 12
drwxr-xr-x 1 ning ning  184 4月   2 15:04 gcc-linaro-aarch64-elf-7.2.1-2017.11
drwxr-xr-x 1 ning ning  196 4月   2 14:59 gcc-linaro-aarch64-linux-gnu-6.3-6.3.1-2017.02
drwxr-xr-x 1 ning ning  196 4月   2 14:58 gcc-linaro-aarch64-linux-gnu-7.3.1-2018.05
drwxr-xr-x 1 ning ning   94 4月   2 15:00 gcc-linaro-aarch64-none-elf-4.8-2013.11
drwxr-xr-x 1 ning ning   88 4月   2 15:04 gcc-linaro-arm-none-eabi-4.8-2013.11
drwxr-xr-x 1 ning ning  208 4月   3 15:32 images
drwxr-xr-x 1 ning ning   56 4月   2 15:05 images_upgrade-afb8bb25ae2983d9851c69395b85a55f36376f16
-rw-r--r-- 1 ning ning 5543 4月   3 11:38 linux-5.0.4_0.5_arm64.buildinfo
-rw-r--r-- 1 ning ning 2027 4月   3 11:38 linux-5.0.4_0.5_arm64.changes
drwxr-xr-x 1 ning ning 1056 4月   3 13:24 linux-mainline-5.0.4
drwxr-xr-x 1 ning ning  266 4月   2 15:04 toolchains
drwxr-xr-x 1 ning ning 1022 4月   3 13:24 u-boot-mainline-ee168783ae889cf449cee36cc1e51e108a210ed4
drwxr-xr-x 1 ning ning  208 4月   2 15:05 utils-108fb1745e84cdd2fc5ca5d764a5ced8085b6552
```
it looks not, I have build bionic + MATE, and stretch + xfce

```
	if [ "$KHADAS_BOARD" == "VIM1" ] && [ "$LINUX" == "mainline" ] && [ "$DISTRIB_RELEASE" == "xenial" ] && [ "$DISTRIB_TYPE" != "server" ] && [ "$DISTRIB_ARCH" == "arm64" ]; then
```
is this why I can't find mali.ko?

**Comment by zhangn1985** [comment]
another question, can lima.ko co-exists with mali.ko?

**Comment by numbqq** [comment]
> it looks not, I have build bionic + MATE, and stretch + xfce
>	if [ "$KHADAS_BOARD" == "VIM1" ] && [ "$LINUX" == "mainline" ] && [ "$DISTRIB_RELEASE" == > "xenial" ] && [ "$DISTRIB_TYPE" != "server" ] && [ "$DISTRIB_ARCH" == "arm64" ]; then
> is this why I can't find mali.ko?

Yes, you need to choose `xenial` + `mate`.

> another question, can lima.ko co-exists with mali.ko?

Not sure, you can try.

**Comment by zhangn1985** [comment]
do you know how to cross compile mesa-lima?

**Comment by numbqq** [comment]
I haven't tried cross compile yet, I just compile on VIM1. Some instructions I ever used to compile:
```
sudo apt-get build-dep libgl1-mesa-dri

sudo apt-get install \
    automake libtool \
    bison flex \
    gettext \
    libdrm-dev \
    libexpat1-dev \
    libudev-dev \
    libx11-xcb-dev \
    libxcb-dri3-dev \
    libxcb-dri2-0-dev \
    libxcb-glx0-dev \
    libxcb-xfixes0-dev \
    libxcb-present-dev \
    libxcb-sync-dev \
    libxshmfence-dev \
    libxdamage-dev \
    libxext-dev \
    libxfixes-dev \
    python-mako \
    x11proto-present-dev \
    x11proto-dri3-dev \
    x11proto-dri2-dev \
    x11proto-gl-dev \
	libxrandr-dev

cd mesa-lima

git pull

./configure --with-gallium-drivers=exynos,sun4i,meson,rockchip,lima --with-dri-drivers= --with-platforms=drm,x11 --disable-xvmc --disable-vdpau --enable-debug

./autogen.sh \
     --with-dri-drivers= \
     --with-egl-platforms=x11,drm \
     --disable-xvmc --disable-vdpau \
     --with-gallium-drivers=exynos,sun4i,meson,rockchip,lima

make -j4
make install
```

Aboud cross compile, I hope this will help you: https://github.com/chewitt/LibreELEC.tv/blob/amlogic/packages/graphics/mesa/package.mk

**Comment by zhangn1985** [comment]
https://github.com/khadas/fenix/blob/master/config/functions/build-gpu-deb#L85-L89
and 
https://github.com/khadas/fenix/blob/master/config/functions/build-rootfs#L503-L506

duplicate with some difference?

and UMP is disabled...

udev rules in build_gpu_deb can be removed?

**Comment by numbqq** [comment]
You can't remove the first one, because for legacy kernel if you remove this, then the mali rule will not be applied.

**Comment by zhangn1985** [comment]
@numbqq thank you for accept my patches.

**Comment by zhangn1985** [comment]
@numbqq I find lima is merge to linux/mesa, do you have any plan to make it default for mainlinux build?
