### ISSUE TITLE
[Request] Build on Linux Mint

### ISSUE THREAD

**Issue by CyberManifest** [khadas/fenix#34]
Can you make this to run on Linux Mint (an Ubutu Core distro); right now I have to use a docker session to build with, since I don't use Ubuntu, but instead use Linux Mint.

**Comment by numbqq** [comment]
I don't have `Linux Mint` environment to test, maybe can't work well. My host PC is still `Ubuntu 16.04`, so I use docker to build image all the time, I think it's a good choice to build on other platform with docker.

**Comment by gytisrepecka** [comment]
Linux Mint is pretty much the same Ubuntu. What didn't work out if you try?

I remember I used to build both Ubuntu and Android on Linux Mint host - as long as you have all mentioned toolchains installed, it was straightforward. Of course you must check `gcc` version just to make sure.
