### ISSUE TITLE
EMMC install for mainline kernel & uboot

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#39]
@numbqq I think it's time for enable EMMC install for mainline kernel and uboot.

refer to: [linux-meson](http://linux-meson.com/doku.php), mainline uboot supports for vim1/2 is done, and mainline kernel for vim1/2 is almost finished.

and @150balbes has scripts for EMMC install.
https://github.com/150balbes/Build-Armbian/blob/master/packages/bsp/aml-s905/install-2018.sh

could you have a look?

**Comment by numbqq** [comment]
Hello @zhangn1985 ,

Yes, you are right..

Actually, I have tried to do this months ago, I have created a repo for this: https://github.com/numbqq/install_to_emmc

But for some other reasons, this hasn't been done, and will do this in next step...

**Comment by zhangn1985** [comment]
@numbqq if you want tester, I can help.

**Comment by zhangn1985** [comment]
@numbqq there are 2 kinds of EMMC images
1, flashable EMMC image which is created by aml_image_v2_packer, finally it will be flashed by aml-flash-tool through USB Type-C. this is used by Khadas.
2, installable EMMC image which firstly is SD image, then can be installed to EMMC. this is used by communite.

it's very long time since you said start to try, so could you share your status and tell me which do you choose.

**Comment by numbqq** [comment]
Hello @zhangn1985 

>1, flashable EMMC image which is created by aml_image_v2_packer, finally it will be flashed by aml->flash-tool through USB Type-C. this is used by Khadas.

This will remain for legacy kernel.

>2, installable EMMC image which firstly is SD image, then can be installed to EMMC. this is used by 
> communite.

We will release a script to write SD image with legacy kernel or mainline kernel to the eMMC.

Due to some other works, this hasn't been done, yet...But we will do it.

Thanks.

**Comment by CyberManifest** [comment]
> Hello @zhangn1985 ,
> 
> Yes, you are right..
> 
> Actually, I have tried to do this months ago, I have created a repo for this: https://github.com/numbqq/install_to_emmc
> 
> But for some other reasons, this hasn't been done, and will do this in next step...

When I visit that URL, it says: "This repository is empty." Is there any progress or leeway on this?

**Comment by numbqq** [comment]
@zhangn1985 @CyberManifest 

Finally, the eMMC install script has added: https://github.com/khadas/fenix/commit/15d260c2e1ff0f4f932c6d3a03a89c33b4f81bbd
