### ISSUE TITLE
patches for sun4i?

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#42]
just check patches for kernel 5.0.4, I find 2 patches:

> 0057-ASoC-sun4i-i2s-multichannel-updates.patch
> 0058-ASoC-sun4i-i2s-multichannel-updates-fixes.patch

are they really needed?

and for `0079-arm64-dts-VIM1-add-bluetooth-node.patch` is merged to 4.20?

**Comment by numbqq** [comment]
NO, should be removed...
