### ISSUE TITLE
mainline linux doesn't need bluetooth-khadas.service

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#46]
by my test mainline linux doesn't need bluetooth-khadas.service, 3rd party hciattach is also not needed.

thus can make code and bluetooth logic much clean.

**Comment by numbqq** [comment]
> by my test mainline linux doesn't need bluetooth-khadas.service

Yes, so the script for mainline kernel is empty. Maybe I need to disable it completely.
