### ISSUE TITLE
missing kvim.dtb symlink for vim mainline emmc

### ISSUE THREAD

**Issue by tavoc** [khadas/fenix#5]
in line 610 from file /scripts/create_image.sh

there seems to be missing a symlink for kvim.dtb

I was trying to build for VIM1 with mainline linux, 2015 uboot a ubuntu_server16 image and got always a error about a missing symlink.
It can be fixed with

`## Fixup upgrade dtb link
fixup_dtb_link() {
        ret=0
        cd $UPGRADE_DIR
        rm -rf kvim.dtb

        case "$LINUX" in
                4.9)
                        ln -s ../../linux/arch/arm64/boot/dts/amlogic/$LINUX_DTB kvim.dtb
                        ;;
                3.14)
                        ln -s ../../linux/arch/arm64/boot/dts/$LINUX_DTB kvim.dtb
                        ;;
        mainline)
                        ln -s ~/project/khadas/ubuntu/build/images/linux-mainline/meson-gxl-s905x-khadas-vim.dtb kvim.dtb
                        ;;
                *)
                        error_msg $CURRENT_FILE $LINENO "Unsupported linux version:$LINUX"
                        ret=-1
        esac

        cd -

        return $ret
}
`

Another problem: I cant get this image to burn to emmc, the amlogic tools always give an error. 
Image here: http://ovh.to/NnGVV5P

**Comment by numbqq** [comment]
Hi tavoc,

Mainline linux only support SD/USB installation now. If you want to install mainline linux to eMMC, more patches are needed. Please refer to [this](https://github.com/numbqq/linux/commit/3e80c0fde99b27f678dd264061f158b2bcbfa11c).
