### ISSUE TITLE
Missing serial# and cpuid# on latest 20190830 firmware

### ISSUE THREAD

**Issue by giminni** [khadas/fenix#51]
**Describe the bug** *A clear and concise description of what the bug is.*
I cannot found the serial and cpuid info in u-boot, please expose this also in /proc/cmdline

**To Reproduce** *Steps to reproduce the behavior:*
`printenv serial#` I get **1234567890**
cpuid is not set

**Expected behavior** *A clear and concise description of what you expected to happen.*
Can read the serial and cpuid number

**Additional context** *Add any other context about the problem here.*
There are some spurious keys like serverip and netmask I guess are left from some DHCP/TFTP tests

**Comment by numbqq** [comment]
> I cannot found the serial and cpuid info in u-boot, please expose this also in /proc/cmdline

Yes, we can do it.

> There are some spurious keys like serverip and netmask I guess are left from some DHCP/TFTP tests

Yes, it is.
