### ISSUE TITLE
Cannot Build Debian Stretch

### ISSUE THREAD

**Issue by vozeldr** [khadas/fenix#56]
I attempted a couple of times to build an image for Debian and was receiving an error. I instead built for Ubuntu and everything was fine. I was attempting to do the build via docker. The error I received was: 

```
Info: Building WiringPi packages...
Info: Building Kodi packages...
cp: cannot stat 'stretch/arm64/*.deb': No such file or directory
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1
```

Below are the bits from setenv:

```
#VERSION: 0.7

#KHADAS_BOARD=VIM3
#VENDOR=Amlogic
#CHIP=A311D
#LINUX=4.9
#UBOOT=2015.01
#DISTRIBUTION=Debian
#DISTRIB_RELEASE=stretch
#DISTRIB_TYPE=lxde
#DISTRIB_ARCH=arm64
#INSTALL_TYPE=EMMC
```

**Comment by numbqq** [comment]
Thanks for your feedback. I will look into this issue.
