### ISSUE TITLE
use async populate rootfs to replace revert of upstream patch.

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#60]
https://lists.ubuntu.com/archives/kernel-team/2009-December/007544.html

this patch is for speed up cold boot, maybe could replace: 0092-Revert-arm64-dts-rockchip-Add-capacity-dmips-mhz-att.patch

do you have time to evaluate this patch?

**Comment by numbqq** [comment]
Thank you.
Yes, I will check this once my computer arrived. (I'm working at home)

**Comment by zhangn1985** [comment]
已验证。
https://github.com/zhangn1985/build/commit/7afc022e517879dc9b73775efb02a3feba883759

**Comment by zhangn1985** [comment]
https://github.com/zhangn1985/build/blob/master/patch/u-boot/khadas/5-clk-init.patch

this is better
