### ISSUE TITLE
khadas mcu&fun driver issues.

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#62]
Hi, nick

after build failed with edge/R3399 kernel config, I start to read the drivers.
the driver directly extern some functions from meson-thermal driver, make them build failed with edge kernel config.

it looks like implement 2 major function: system control (USB3/PCIE switch, MCU rest), and fun control.
I guess it should be implemented as MFD with 2 sub-functions: sysfs system control driver, fun control driver (could it use cooling framework? make it more generic to fit it to edge, or future devices)

**Comment by numbqq** [comment]
MCU driver will add to upstream soon.
https://forum.khadas.com/t/mainline-linux-khadas-mcu-driver/7639
