### ISSUE TITLE
Problem Vim2 and armhf

### ISSUE THREAD

**Issue by tib-kpl** [khadas/fenix#7]
Hello,
I create an image with armhf fenix and I install this image on my vim2 with usb burning tool but my vim2 does not start. I only have the Khadas bootlogo on my screen.

On fenix I chose the options, kernel v4.9, Ubuntu mate, armhf, eMMC.

When I create an image in arm64 it works.

Do you have an idea to make a linux armhf image work on vim2?

**Comment by numbqq** [comment]
It seems the new version script uInitrd is not correct for armhf.

I will fix this...

**Comment by numbqq** [comment]
Hi tib-kpl,

Can you update the Fenix repo and try again?

https://github.com/khadas/fenix/commit/2633d302ed2ef77cd340b12ce4dd5750fd8ecf9b

**Comment by tib-kpl** [comment]
Hi numbqq,

I thank you for answering me so quickly.

I made a new image with your new version. My vim2 starts but when I write the command "uname -m" in the terminal it always returns me aarch64 it's normal? I'm trying to install teamviewer on my vim2 but it seems to me that teamviewer only works on armhf and here teamviewer does not work.

**Comment by tib-kpl** [comment]
Hi numbqq,

Is it possible to have an image with an armhf kernel for vim2?

**Comment by tib-kpl** [comment]
Hi numbqq,

Do you think the 32 bit will be supported?

**Comment by numbqq** [comment]
Maybe not.
