### ISSUE TITLE
VIM3L debian buster image does not boot

### ISSUE THREAD

**Issue by jiez** [khadas/fenix#77]
I created a Debian buster image for VIM3L, but it does not boot. When power on, the white LED is on for several seconds, then off. There is no output from HDMI. The configuration I use is

===========================================
#VERSION: 0.8.3

#KHADAS_BOARD=VIM3L
#VENDOR=Amlogic
#CHIP=S905D3
#LINUX=mainline
#UBOOT=mainline
#DISTRIBUTION=Debian
#DISTRIB_RELEASE=buster
#DISTRIB_TYPE=server
#DISTRIB_ARCH=arm64
#INSTALL_TYPE=SD-USB

===========================================

I use the latest Ubuntu 18.04 as the host.
fenix d2f0c3562475b74baaf6f97b33cb04e12f35bae4

Thanks,

**Comment by jiez** [comment]
The cause might be related to mainline kernel or u-boot. Because if I choose 4.9 kernel and older u-boot, it boots OK.

**Comment by numbqq** [comment]
Thanks for yor feedback, we will check this issue.

**Comment by numbqq** [comment]
@jiez 

I checked with latest source code. And the image works well. HDMI display OK.

I erase the eMMC and bootup from SD card completely.

```
khadas@Khadas:~$ 
khadas@Khadas:~$ 
khadas@Khadas:~$ cat /etc/fenix-release 
# PLEASE DO NOT EDIT THIS FILE
BOARD=VIM3L
VENDOR=Amlogic
VERSION=0.8.4
ARCH=arm64
INITRD_ARCH=arm64
INSTALL_TYPE=SD-USB
IMAGE_RELEASE_VERSION=V0.8.4-20200424
khadas@Khadas:~$ 
khadas@Khadas:~$ 
khadas@Khadas:~$ lsb_release -a         
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
khadas@Khadas:~$ 
khadas@Khadas:~$ 
khadas@Khadas:~$ 
khadas@Khadas:~$ uname -a
Linux Khadas 5.6.0 #0.8.4 SMP Fri Apr 24 21:33:22 CST 2020 aarch64 GNU/Linux
khadas@Khadas:~$ 
khadas@Khadas:~$ 
khadas@Khadas:~$ 
khadas@Khadas:~$ 
khadas@Khadas:~$ 
```

**Comment by jiez** [comment]
Thanks. But after I updated fenix to the latest (241efba) and rebuilt the image, it still does not boot. eMMC is not erased and still has the android coming with it.

**Comment by jiez** [comment]
I noticed that there are some new commits. So I tried again with the latest (b91a4ce). It still does not boot. I tried SD card and USB drive. Neither works.

#KHADAS_BOARD=VIM3L
#VENDOR=Amlogic
#CHIP=S905D3
#LINUX=mainline
#UBOOT=mainline
#DISTRIBUTION=Debian
#DISTRIB_RELEASE=buster
#DISTRIB_TYPE=server
#DISTRIB_ARCH=arm64
#INSTALL_TYPE=SD-USB

**Comment by jiez** [comment]
I also tried to build it on a newly installed Ubuntu 20.04 host. The resulted image still does not boot on VIM3L.

**Comment by jiez** [comment]
According to the discussion
https://forum.khadas.com/t/mainline-kernel-and-uboot-do-not-boot-on-vim3l/8209/15
this issue was caused by the uboot in eMMC. After eMMC is erase, it boots OK.
