### ISSUE TITLE
[VIM3] Debian / ubuntu mainline build failed

### ISSUE THREAD

**Issue by Pea13** [khadas/fenix#82]
Hello,

I'm trying to build a new image with the latest fenix (0.8.4) for both ubuntu (focal) or Debian (10) with mainline uboot, mainline kernel and server mode.
These 2 builds fail with this message: 

make[1]: Leaving directory '/home/khadas/fenix/build/linux-mainline-5.6'
Info: Building debs...
Info: Building package: linux-u-boot-vim3-mainline
dpkg-deb: error: parsing file '/home/khadas/fenix/build/images/.tmp/linux-u-boot-vim3-mainline_0.8.4-_arm64/DEBIAN/control' near line 2 package 'linux-u-boot-vim3-mainline':
 'Version' field value '0.8.4-': revision number is empty
make: *** [Makefile:7: all] Error 2

Any ideas to fix this ?
Thank you.
Regards,

**Comment by templarundead** [comment]
I also encountered this problem

**Comment by Pea13** [comment]
This commit https://github.com/khadas/fenix/commit/b91a4ceef8a8a48713d9fb15242b087689cd6e26 fixes the issue :)
Thank you.
