### ISSUE TITLE
VIM/Amlogic:  update Xserver or disable pageflip for modesetting

### ISSUE THREAD

**Issue by zhangn1985** [khadas/fenix#93]
upstream issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/3143

我测试过升级xserver可以解决这个问题。

升级xserver可以用我的build rules: https://github.com/zhangn1985/xserver-build-rules , 配合xserver主线： https://gitee.com/mirrors_addons/xserver
同时需要升级fbdev，可以使用: https://salsa.debian.org/xorg-team/driver/xserver-xorg-video-fbdev

因为upstream issue提到的xserver的patch就是disable pageflip，所以也可以禁止modesetting driver的pageflip。
`man modesetting`

```
       Option "PageFlip" "boolean"
              Enable DRI3 page flipping.  The default is on.
```

**Comment by numbqq** [comment]
对，这个问题之前在Ubuntu上碰到过，我后来是通过升级mesa版本来来解决的，还没升级过xserver，到时试试你提供的方式，谢谢！

**Comment by zhangn1985** [comment]
我升级xserver之后，S905x的glmark2得分从120到了170，比较吃惊，应该是关闭pageflip的结果吧。

**Comment by zhangn1985** [comment]
我的rules刚升级了，有一个错误，昨天晚上发现的。

**Comment by zhangn1985** [comment]
关闭这个问题。

另外，如果拔出鼠标，glmark2-es2的跑分会到190+
