### ISSUE TITLE
build errror

### ISSUE THREAD

**Issue by dshame** [khadas/fenix#95]
E: Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/a/avahi/libavahi-common-data_0.7-4+b1_arm64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:927084b7b7e0f2cd9a7ffd371cfb0139c0def9e96fc0bf2cf270563cfd6bf95b
    - MD5Sum:c1e955a381a95c3c1cc75107d067d583 [weak]
    - Filesize:122236 [weak]
   Hashes of received file:
    - SHA256:eb329c93d0d210d80e801f6202308940ba0e437be3671153200ad223d8c61233
    - MD5Sum:7568a63cdb6868df91ac927edf80f850 [weak]
    - Filesize:122236 [weak]
   Last modification reported: Wed, 10 Oct 2018 08:28:55 +0000
E: Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/a/atlas/libatlas3-base_3.10.3-8_arm64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:0d279311352ede6421622bf913f633f388248ff267c3f600ed6a4a3382d98aa0
    - MD5Sum:0eb35cf1e58d189d7c9af03773cd95cc [weak]
    - Filesize:2408572 [weak]
   Hashes of received file:
    - SHA256:a20e9f18b1357cf797e655fd5bceefb3befa3237ae633ea77bb1a4326d5bb055
    - MD5Sum:bfa4b681c8b548c1e58e0b956c47f871 [weak]
    - Filesize:2408572 [weak]
   Last modification reported: Tue, 22 Jan 2019 12:27:59 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Cleanup...
make: *** [Makefile:7：all] 错误 100

**Comment by dshame** [comment]
.-/+oossssoo+/-.               code@code-Standard-PC-i440FX-PIIX-1996 
        `:+ssssssssssssssssss+:`           -------------------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-2.8) 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-42-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 27 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1590 (dpkg), 6 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x985 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel (Haswell) (8) @ 3.599GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: 00:02.0 Red Hat, Inc. QXL paravirtual graphic card 
      -+sssssssssssssssssyyyssss+-         Memory: 990MiB / 5899MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.

**Comment by numbqq** [comment]
> E: Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/a/avahi/libavahi-common-data_0.7-4+b1_arm64.deb Hash Sum mismatch

It's a network issue, please try again.

**Comment by dshame** [comment]
is hash match error ?
where i can change the china  mirror ?

**Comment by numbqq** [comment]
You can change other mirror here:

https://github.com/khadas/fenix/blob/master/config/config#L240

**Comment by dshame** [comment]
thx
